### ISSUE TITLE
Suggestion: Automatically add relevant combat dice pool to weapon accuracy

### ISSUE THREAD

**Issue by Tardog** [Aliharu/Foundry-Ex3#1]
Hi,

currently the accuracy field on weapon slots determines the dice pool used for the attack for individual characters, exactly the way it works for quick characters. Our group had a bit of trouble adjusting to this, because the expectation for PCs is that weapon accuracy is added to the attack dice pool (Dexterity + Melee) on withering attacks on the fly.

If you are interested in making this change, but don't have the time or want to prioritize other changes, I could make a PR.

**Comment by Aliharu** [comment]
This was done deliberately to avoid annoyances with stuff like elemental bolt attack but ill look into it using the normal ability attribute dice roll.

**Comment by Tardog** [comment]
Thank you. Much appreciated! It's really just a quality of life improvement.

**Comment by Aliharu** [comment]
Change done in 0.6.2
