### ISSUE TITLE
Can't install via FoundryVTT Game System - 1.0.5 zip not found 

### ISSUE THREAD

**Issue by xerosagas** [Aliharu/Foundry-Ex3#16]
Whenever I try to install this game system from Foundry I get an file not found error. Also, the version in the Foundry UI doesn't match up with what's being downloaded

Repro steps:
1. Launch Foundry and log in to setup
2. Click on Game Systems
3. Click Install Systems
4. Search for "Exalted"
5. On Exalted Third Edition, note the version reads 1.0.4.
6. Click Install.

Expected: The version in Foundry should match the latest, and install successfully
Actual: Foundry throws an error attempting to download version 1.0.5.

`Error: An unexpected error occurred when downloading file https://github.com/Aliharu/Foundry-Ex3/releases/download/v1.0.5/release1.0.5.zip: Not Found
    at fetchWithTimeout (file:///foundryvtt/resources/app/common/utils/http.mjs:42:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///foundryvtt/resources/app/dist/files/downloader.mjs:1:616`
    
    
![image](https://user-images.githubusercontent.com/4909903/197403809-0860c39e-8ec0-40f6-8cac-6277a7eda83e.png)

**Comment by Aliharu** [comment]
Should be fixed with the release of 1.0.5
