### ISSUE TITLE
Token Effects aren't appearing.

### ISSUE THREAD

**Issue by Donnerino12** [Aliharu/Foundry-Ex3#18]
Hey, I've been messing around with the new update, thanks a lot for the work you've all put in. I installed the Token FX into my exalted game and started trying to get the effects to show up to see how they look. Unfortunately, either by manually adjusting the anima level or moving it up by using charms, the effects don't appear to be showing. I have the lib wrapper installed, and I've made sure to turn the option on. I'm unsure if there is something I'm missing or if there is something going wrong. I don't see any errors showing up in the console.

Thanks!

**Comment by Aliharu** [comment]
Check the "Dot Colors" field on your token's sheet.  Make sure its not #000000.  Ill add a warning that pitch black doesn't work with the effects next update

**Comment by Donnerino12** [comment]
I've checked all my player's sheets, and they are all set to their various dot colors, none of them are #000000.

**Comment by Aliharu** [comment]
I just ran a bunch of tests and its working for me so i don't know what's going on.

**Comment by Donnerino12** [comment]
Alright, well, I'll see if I can get you anything else to work off of. It's no big deal.
