### ISSUE TITLE
Creation macro from attacks decisive and witherings

### ISSUE THREAD

**Issue by carlos-decastro** [Aliharu/Foundry-Ex3#2]
Hi, 

I'm trying to create a macro for my decisive attacks and witherings of my main weapons, but I don't know how to run the function that calls openAttackDialogue, could you help me with that? If you prefer, call me to Discord Carlos Castro#9944

**Comment by Aliharu** [comment]
openAttackDialogue(this.actor, attribute, ability, accuracy, damage, overwhelming, attackType(withering, decisive,gambit), weapontype);
