### ISSUE TITLE
Minimums Breaking Charm Importer

### ISSUE THREAD

**Issue by SamuraiMujuru** [Aliharu/Foundry-Ex3#22]
When importing charms copied directly from the Exalted 3E core book any charm that has a minimum  line that is split breaks the importer. If importing one charm importing just fails, if importing multiple the charm with a broken line and all subsequent charms won't import. 
It's easily worked around (collapse the split rows into one), but there's no notification of failure.
![Screenshot_20230118_103806_ReadEra Premium](https://user-images.githubusercontent.com/123003716/213240761-1be5c425-9e38-4294-83dc-33e824a5fb10.jpg)

Book text screenshot included as example.

**Comment by Aliharu** [comment]
Added some text to tell the user to remove line breaks
I've also added some code to work around line breaks but its not 100% full proof
