### ISSUE TITLE
Charm Importer appears to ignore Essence mins

### ISSUE THREAD

**Issue by leojackson** [Aliharu/Foundry-Ex3#23]
Importing a Charm formatted according to the example results in a Charm where the Essence is set to 0, even when the Charm is properly specified in the importer with an Essence value above 0.

**Example input:**

```
Testing Import Prana
Cost: 3m, 1i, 2wxp; Mins: Lore 2, Essence 1
Type: Supplemental
Keywords: None
Duration: Instant
Prerequisite Charms: Sourcing Data Method
With this charm, the Lawgiver tests the import functionality of the Exalted: Third Edition system in Foundry v10. When making a Social Influence roll to report an issue in Github, make the roll with double 9s, and reroll 1s until 1s fail to appear.
```

**Result:**

The Charm is imported with an Essence of 0. All other data appears to be correct.

![TestingImportPrana-MainScreen](https://user-images.githubusercontent.com/9401450/213664021-cbfa6315-f8fb-4535-bd89-7da39079d7c9.png)
![TestingImportPrana-CostScreen](https://user-images.githubusercontent.com/9401450/213664358-63391dd5-2283-4ca7-b8a7-bfedcb554e30.png)

System info:

Foundry v10, build 291, running on The Forge
System: exaltedthird, v1.6.2

**Comment by Aliharu** [comment]
Should be fixed in 1.6.3
