### ISSUE TITLE
Dice rolls fail with DAE when effects are inactive

### ISSUE THREAD

**Issue by leojackson** [Aliharu/Foundry-Ex3#25]
While the module [Dynamic Active Effects](https://gitlab.com/tposney/dae) is enabled, if there are any Active Effects that are inactive for a character, all of that character's dice rolls will fail to occur. This is new behavior starting some time between 1.7.2 and 1.7.6, but still exists in 1.8.2.

**Expected behavior**
Inactive effects are ignored. Dice rolls occur as if they do not exist.

**Actual behavior**
Dice rolls fail to occur for characters with inactive Active Effects. In the console, the dice count is "NaN," resulting in roll descriptors like "NaNd10cs>=7". Characters without inactive Active Effects are unaffected.

In Foundry-Ex3 v1.7.6, the failed dice roll is produced in chat as if "NaN" is the number of dice. No dice are rolled.
In Foundry-Ex3 v1.8.2, no chat output is produced, but the result of "NaN" is still visible in the console.

This behavior does not occur when the DAE module is active in the dnd5e or pf2e systems.

**Versions**
Core: v10.291
System: Foundry-Ex3 v1.8.2
Module: Dynamic Active Effects 10.0.20

**Comment by Aliharu** [comment]
Dynamic Effects is specified as a dnd5e module and not compatible with Ex3.

Looking at the specifics dynamic active effects are breaking the health calculation code

There will be a fix next patch to the roll breaking but health calculations will still be broken by dynamic active effects and the module is not recommended
