### ISSUE TITLE
Advanced Animation Macros

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#28]
![image](https://user-images.githubusercontent.com/54109677/230663942-e4634b0c-4f58-4361-b7e5-9f431dd96cb9.png)

https://user-images.githubusercontent.com/54109677/230663951-01acedfe-5961-4698-b647-24c06621bc8f.mp4

![image](https://user-images.githubusercontent.com/54109677/230664001-c87dcd2c-a165-4000-ac10-97e9d23c1561.png)

I've been asking around on the JB2A discord and they've directed me here to inquire about how to do this. I can get exalted to trigger the weapon effect easily enough by using the custom input. But I want it to trigger like the macro I've outlined above. How can I go about having the custom input call to the above macro to trigger it, when the weapon damage roll is executed, the same way it would JP2A's animations?

Thanks!

**Comment by Aliharu** [comment]
The built in sequencer trigger only works on 1 animation file.

If you want to do something more complex you are going to need to do a bit of a workaround

Make a charm,  go to the macro tab, paste your animation in the "Damage Macro".  Then add it to any dice roll you want to trigger the specific animation on.

Example Animation

//Use actorToken for the weapon users token.  and this.object.target for the targets token.
const actorToken = this._getActorToken();                        
new Sequence()
    .effect()
    .file('jb2a.maul.melee.standard.white')
    .atLocation(actorToken)
    .stretchTo(this.object.target)
    .waitUntilFinished(-1100)
    .effect()
    .file("jb2a.impact.ground_crack.orange")
    .atLocation(this.object.target)
    .scale(0.5)
    .belowTokens()
    .play();

**Comment by Pentazer** [comment]
Hmm okay. That works, as a work around, but it's a little clunky. For now, I guess I can work with that. But ideally that could hopefully be supported in the future.

Thanks!

**Comment by Aliharu** [comment]
In 1.10.0 there is now a text input in weapons to input a custom macro.  Put in the text chunk similar to my example into the weapon macro and it will trigger when you attack with it.

**Comment by Pentazer** [comment]
Yes worked perfectly, thank you!
