### ISSUE TITLE
Custom Abilities?

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#30]
Hey, so I run Exalted Modern and there's some abilities I wanted to be able to tie into weapon and charm use. I tried using craft and martial arts as placeholders, but they don't work quite right. Is there a way to implement adding new abilities such as: Drive, Pilot, Computers, Firearms, etc. in a way that I can hook them in on charms and select them for attacks (such as using Dex + Firearms for using a gun)) that is distinct from archery?

Thanks for supporting this amazing system on foundry and all your fantastic work!

**Comment by Aliharu** [comment]
I can look into merging martial arts and craft into a 1 combined list.

What are the issues with martial arts and crafts for custom abilities other than not being able to select them on weapons/charms?

**Comment by Aliharu** [comment]
As of 1.11.0 This should be supported

**Comment by Pentazer** [comment]
Thanks! however it doesn't seem to be working.
![shot1](https://user-images.githubusercontent.com/54109677/233796458-9eb84cfb-6265-403c-a79d-b97e993d432a.jpg)
![shot2](https://user-images.githubusercontent.com/54109677/233796460-24e35ef1-470f-4e18-8f5b-73197be4aac5.jpg)
![shot3](https://user-images.githubusercontent.com/54109677/233796462-5807e53f-7701-48c7-800d-4e68d1d96f73.jpg)
![shot4](https://user-images.githubusercontent.com/54109677/233796464-c50953bc-a242-4414-8453-22362aece2fc.jpg)
As seen in figure 1 and 3. The firearms skill can be created and does register as a roll, it also can be assigned to the weapon's ability.

However in figure 2 and 4, when attempting to roll firearms alone, it only is rolling the 3 dexterity. Likewise, when rolled as an attack you can see it's still only rolling the 3 dexterity. I attempted this by changing the firearms independently of the dexterity attribute, but no matter what value firearms is at, it's only rolling the attribute and not attribute + ability.

**Comment by Aliharu** [comment]
Okay, 1.11.1 hotfix is out.  Try it now

**Comment by Pentazer** [comment]
Yup, that's got it! all working now. Thank you muchly, from me and my group!
