### ISSUE TITLE
Custom Ability Bug

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#31]
![shot1](https://user-images.githubusercontent.com/54109677/236638193-ee13f24a-3a2b-4284-8075-87c65e85f21e.jpg)
![shot2](https://user-images.githubusercontent.com/54109677/236638194-3d9d769d-3c9d-4aaf-a9c8-df83e14e0aca.jpg)

There seems to be an issue with custom abilities being registered. As seen in figure 1, Firearms, Operate Vehicle, Pilot, Computers and Artillery have been created, have specialties and dots applied.

However in figure 2, weapons are not registering them, so I'm unable to select artillery or firearms for associated weapons. I tried this on multiple and they're not showing.

if I delete the ability and re-create it, it allows it to work for that instance of the game, but it seems if I close the game and start it up later, the abilities don't register again and all the weapons set to firearm or artillery is now set to archery.

**Comment by Aliharu** [comment]
So, the core issue is that right now all custom ability logic assumes you are linking to the abilities in your actor.

If you are trying to make items that aren't tied to actors, any custom ability logic won't currently work.  This is a limitation of Foundry as Foundry hates trying to link items together for exactly this reason.

Custom abilities showing up in the weapons if the weapon doesn't belong to an actor is a bug.

**Comment by Pentazer** [comment]
Oh interesting. So I have to equip the items from the pool first, then assign the ability parameters and then it will remember them?

**Comment by Aliharu** [comment]
Yeah so here is the current implementation

When you open an item it checks the parent actor for custom abilities and adds them to the list.  Each actors charms/weapons/etc should only show custom abilities from that actor.

There is a bug currently where its not clearing the custom abilities when other items are opened so that's why its showing up for you before you reset the world.  Ill have that fixed soon

**Comment by Pentazer** [comment]
Gotcha. I'll give that a go. Thanks!
