### ISSUE TITLE
Firefox Error in Foundry 11 EX3

### ISSUE THREAD

**Issue by mparker546** [Aliharu/Foundry-Ex3#32]
Loading EX3 System in Foundry 11 in Firefox throws this error:
```
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    onload index.js:126
index.js:126
    onload index.js:126
```
![image](https://github.com/Aliharu/Foundry-Ex3/assets/64708616/d1822d56-b339-4745-b2c5-be42be9d4e2c)

Workaround: Works in Chrome fine.

**Comment by Aliharu** [comment]
This does not happen when i try it in Firefox.  This might be a core Foundry issue and not something with the Ex3 module judging by the error message.

**Comment by Aliharu** [comment]
I dug around, I did not run into this specific issue but i ran into a different issue regarding SVGs while testing on firefox.  I will have a change that hopefully will fix this issue next patch not 100% certain.

**Comment by Aliharu** [comment]
This should be fixed now.  Closing
