### ISSUE TITLE
2.0.4 Error

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#34]
![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/d915ac45-24c5-467a-95d0-75a3d7a6da09)
Seems like there is a 2.0.4 version but it can't be found?

**Comment by Aliharu** [comment]
Looks like updating github without making a release still causes foundry to see a new version

2.0.4 is out and it sohuld fix that
