### ISSUE TITLE
Poison not applying?

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#35]
I see that poison effects have been added to weapons, I think this is entered correctly?
![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/16a494a9-99da-492c-b154-9b2c5bc13a37)
However when the attack connects using this weapon, I don't see anything having been done in the roll results nor do I see the effect applied to the target and I don't see any damage being dealt at the end of each round. Am I doing this right? I checked the readme wiki but it doesn't mention how poisons are used anywhere.

**Comment by Aliharu** [comment]
You need to set the damage type to something

**Comment by Pentazer** [comment]
oh whoops, I forgot to include that in the screenshot. I already tested it with bashing (initiative) and lethal (initiative) and neither of those seemed to work.

**Comment by Aliharu** [comment]
Okay so, hitting with a successful decisive attack is what triggers poison.

The issue with initiative not changing is a bug and ill fix that (you can fix that by adding a value to Effect Start Turn in the Active Effect Sheet).  But you should see an active effect being added when a target is struck with a successful decisive attack.

**Comment by Pentazer** [comment]
I discovered some new problems with the poison system. I don't have time to post the details right now, but this evening I'll post the step-by-step and the screenshots showing the issues. Looks like it applies sometimes, but not after the first time, no longer removes the effect and sorta bugs out all status effects.

**Comment by Pentazer** [comment]
"Bleeding Effect"
Fig 1.
![Bleeding1](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/0b18abff-0313-4b89-917d-f61c9a3fd376)
Fig 2.
![Bleeding2](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/59a77cd4-18a9-40b1-9888-7118351acaf5)
Fig 3.
![Bleeding3](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/7a5df047-8c99-4dbc-8480-b15c1456c490)
Fig 4.
![Bleeding4](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/8399aef2-925b-432e-b304-881d586acc5e)
Fig 5.
![Bleeding5](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/95be9955-5f17-4a91-9717-2c21835a0455)

"Poison Effect"
Fig 1.
![Poison1](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/9486e344-6381-40f4-98fc-e160a7c6ff47)
Fig 2.
![Poison2](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/398e43f9-59b4-43a2-bb08-91e94047dbb3)
Fig 3.
![Poison3](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/105e07eb-3923-4a28-aa3d-d1c9e41d5755)
Fig 4.
![Poison4](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/c573b622-8204-46a9-bf90-4afc7d5666b5)
Fig 5.
![Poison5](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/f0ac64bb-1fef-4774-9e1e-0dcb13a8e9b9)

***

Okay so, here's what I'm seeing, starting with the Bleeding Effect. Fig 1 is the design for the poison trigger. on dealing decisive damage, the effect procs on the target seen in Fig 2. It has a duration count which at the time of the screenshot, has only 1 round left. So great, that works.  Fig 3 shows that over those 2 rounds, the bleeding effect dealt 2 points of bashing damage, so far, so good. But when the effect ends, the ailment persists as inert in Fig 4. This then seems to have disastrous consequences on all status effects moving forward on that token, until the token itself is deleted. As you can see in Fig 5, now onslaught is bugged up and no longer automatically clears at the start of the entity's turn. Also on issuing a new instance of bleeding, it no longer has a duration applied AND it no longer deals any effect - no bashing damage is dealt anymore. Furthermore, it persists indefinitely as well, meaning as the target continues to receive damage from bleeding weapons, the number of instances of status ailments will just keep piling up.

Next we have the Poison Effect. in Fig 1 you can see the setup. I wanted this one to deal initiative damage and a 1 die penalty to the attack pool. However the target is still bugged from the previous instance, so the poison doesn't have any duration see Fig 2. In Fig 3 you can see that the entity has the 2 status ailments, but has taken no initiative damage at the end of the round. At the beginning of round 7, it should have taken 1 point of initiative damage, but as you can see in Fig 4, it remains at 20 initiative. In Fig 5 you can see that the dice penalty did apply but the effect remains indefinite (I removed onslaught manually) but on round 8, the target's initiative remains at 20.

Also on a side note I'm not sure how the difficulty is supposed to work, is that just a placeholder to know how many die to resist or does it have automation functionality?

**Comment by Aliharu** [comment]
Difficulty is just visual.

Ill take a look at this.  Something in a recent Foundry patch has been bugging up Active Effects so this might be related to that

**Comment by Aliharu** [comment]
I am unable to reproduce some of the issues you were running into with poisons effecting onslaught and such

in 2.2.1 I have made it so poisons inflicted by weapons will delete themselves when you hit Duration 0.  Previously poisons would not inflict damage unless they had a duration above 0.

**Comment by Pentazer** [comment]
Let me give that a test and see.

**Comment by Pentazer** [comment]
Round 1
![Round1](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/5ef8b06c-b3a5-463c-aac0-9c0a0bce3552)
Round 2
![Round2](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/ead19d8d-5bdf-410d-9e92-89441213e24a)
Round 3
![Round3](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/6a03d3c7-9dcc-4a0f-84a6-b578147a3117)
Round 4
![Round4](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/7cacba01-12f4-40c3-b762-ecfab2cc8c91)

Well! based on the above using the Bleeding effect, looks like that's working.
I then tested this with the poison effect that deals initiative damage and a 1 die penalty instead of health damage and that worked too. Status ailments are now deleting themselves when they run out of duration and their duration is correctly incrementing.

Thanks!
