### ISSUE TITLE
How to Lunar?

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#36]
Not really a bug, but I'm not sure how lunars work, how to transform a character from one from to another, collect hearts blood etc. I checked the wiki but it doesn't look like it's been updated with how to configure a lunar character.

**Comment by Aliharu** [comment]
There is an item list on lunars for their various shapes that you can link to different Actors.  This isn't needed for the actual functionality but will let you directly open their sheets

How 2 Link a Lunar to an Animal Form
-Make an NPC statblock for the animal
-In Sheet Settings Enable 'Lunar Animal Form'
-In the effects tab there will now be an input for lunar form.  Select the lunar you want to tie to and hit "Sync".  This will show a popup telling you how syncing works and what will happen.
-Use this statblock whenever a lunar transforms into an animal.  There will have to be some manual stuff like setting their initiative if used in combat.

**Comment by Pentazer** [comment]
Awesome, thank you!
