### ISSUE TITLE
Firefox Unable to Load Assets due to missing SVG attributes

### ISSUE THREAD

**Issue by Taurus-II** [Aliharu/Foundry-Ex3#37]
Firefox requires SVGs to have specified width and height values or it can't load them, resulting in this error and hung loading bars for affected scenes
[Foundry Error Msg.txt](https://github.com/Aliharu/Foundry-Ex3/files/12152662/Foundry.Error.Msg.txt)

**Comment by Taurus-II** [comment]
The specific assets that are failing to load are:
```
systems/exaltedthird/assets/icons/brick-wall.svg
systems/exaltedthird/assets/icons/drop-weapon.svg
systems/exaltedthird/assets/icons/shaking-hands.svg
systems/exaltedthird/assets/icons/grab.svg
systems/exaltedthird/assets/icons/cobweb.svg
```

**Comment by Aliharu** [comment]
Testing it on firefox i found only 1 svg causing the issue, fixing it made it not hang.

Check to see if it works in 2.3.0
