### ISSUE TITLE
Active Effects not working

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#38]
https://github.com/Aliharu/Foundry-Ex3/wiki/Active-Effects

I was using the guide here to attempt active effects that alter parameters but it doesn't seem to be working.
As a test I did the following:
Key | Change Mode | 1
system.attributes.(strength).value | Upgrade | 1

The idea here is that activating the effect will grant +1 strength and then when the effect is deactivated it will automatically remove the +1 strength.

![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/89f25f00-205b-4a57-8bd6-c553e5c48765)
Here is the attributes as they are on this test.

![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/b1caf275-950a-4685-aa55-21685a7936d1)
Activating the effect shows as being active, which is great.

![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/71e1c12f-4d2e-4279-b5ba-8deb1436b889)
But when I check the attributes section, strength remains 1. a new blank attribute has been created. And when I roll any ability that calls to strength, say Athletics 0 with Strength...
![image](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/9ad9e69e-976a-4560-8b11-448480947014)
Only 1 die rolls, which is the 1 Strength, which in theory, it should be 2 die for the +1 due to the active ability.

Am I doing something wrong or is there a problem with the effects?

**Comment by Aliharu** [comment]
I just tested this with "system.attributes.strength.value" and it worked

if you used "system.attributes.(strength).value" then the parentheses are probably throwing it off.

There is an option in settings to enable a dropdown for active effects if you have having issues with the attribute key syntax

**Comment by Pentazer** [comment]
Awesome, yes that worked! Removing the parenthesis fixed it. Also, enabling that option was a great call. Thanks!
