### ISSUE TITLE
Turn order

### ISSUE THREAD

**Issue by tgcgh** [Aliharu/Foundry-Ex3#4]
Players who already played the current turn must not be reordered in front of players who haven't played on the current turn regardless of init since withering attacks can change init while the turn is going on.  Also, some charms allow for iterrupts and so having a way for the GM to reorder the turn at any time could be required some times.

Keep going, nice job!

**Comment by Aliharu** [comment]
No current plans to implement this, a character can be shifted in front of players who haven't taken a turn yet they just don't get another turn if they have already acted this doesn't really break anything so i don't think its required to have manual reording.

In terms of interrupts I don't understand how that would affect the tracker as their turns happen whenever.

Personally I use the Lancer Initiative module to track who has taken turns in combat.
