### ISSUE TITLE
Dice Roll Triggers not working on sorcery

### ISSUE THREAD

**Issue by Pentazer** [Aliharu/Foundry-Ex3#42]
Hi I've been experimenting with damaging spells and as is, it appears like there is no way for a spell to deal damage in this system. So I've been trying the dice roll triggers but those don't seem to be working either.

In this experiment, you'd be throwing12 lethal damage dice as a withering attack, the number of successes are reduced by the target's resistance (which is 3 in this case). So if you rolled 7 successes, you get 4 threshold successes to drain 4 initiative from the target. 

But doesn't look like any of this is applying? Here's what I got:
![SpellDamage](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/98e4f20d-5a2a-4445-a06c-56dcfef338da)

**Comment by Aliharu** [comment]
If you want to have a damage spell you should make a weapon item for it.

**Comment by Pentazer** [comment]
I had considered making spell attacks a weapon but those would require an attack roll and be subject to armour soak wouldn't they? How would you work around those parameters?

**Comment by Aliharu** [comment]
What spell are you trying to emulate?

**Comment by Pentazer** [comment]
None specifically from any of the exalted manuals as they are all decisive spells. These are for withering spell attacks. I managed to cobble together a sorta jank solution involving rolling withering spells as a weapon with no parameters and with no target:
![SpellAttack_01](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/4ccd4887-ecab-4b74-8cc6-ccf1de6fa527)
![SpellAttack_02](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/94d1f999-4e02-4336-b31f-b9d516c9af2e)
![SpellAttack_03](https://github.com/Aliharu/Foundry-Ex3/assets/54109677/22b10e83-983d-413a-b79f-de5a65bff9c9)

It's jank, but it works!

**Comment by Aliharu** [comment]
Cool, ill look at adding triggers to weapons in a following patch.

You could also make a spell with the effects and then add it to a weapon attack
