### ISSUE TITLE
Foundry Light Mode has unreadable buttons

### ISSUE THREAD

**Issue by Lukasrygh23** [Aliharu/Foundry-Ex3#46]
This is how I learned Foundry HAS a light/dark mode setting. On light mode, the text in black on dark coloured buttons is literally unreadable. I know light mode is this weird abomination, but it'd be nice if they were fixed. 

See image. 

![image](https://github.com/user-attachments/assets/aa2cbb53-aba0-40b5-9047-8438010d77d0)

**Comment by Aliharu** [comment]
Should be fixed in 3.2.4
