### ISSUE TITLE
The "Damage" button under Combat cannot hit anything

### ISSUE THREAD

**Issue by Lukasrygh23** [Aliharu/Foundry-Ex3#47]
There's no way to add attack successes, meaning that any roll done witht his button auto-misses if its ever targeted at something with more than 0 defense.

**Comment by Aliharu** [comment]
Attack successes show up in the "Targets" tab attached to the individual targets if you are targeting a character.

**Comment by Aliharu** [comment]
Added the missing Attack Successes text input for rolls that have no target in 3.2.4.

If you are targeting a character you want to look in the targets tab.
