### ISSUE TITLE
Health boxes reversed

### ISSUE THREAD

**Issue by tgcgh** [Aliharu/Foundry-Ex3#5]
Hi, The healthboxes are reversed for lethal and agravated, new lethal and agravated health levels should enter the health bar from the left not from the right.

**Comment by Aliharu** [comment]
Does this break anything?  Its not a trivial change so if it doesn't break anything i'm not planning on changing it.

**Comment by tgcgh** [comment]
Well, it can be worked around but it's kind of a problem for players in the sense that they have to remember to reverse the bar in their head, the heal process should heal left boxes first and so lethal and aggravated are healed before the bashing.  That being said I do understand the pain of recoding stuff and like I said, it is not a deal breaker but less experienced players have to be careful.

**Comment by qeggleston** [comment]
I kind of want to dig in and fix this for myself. @Aliharu would you mind pointing me to the spots where you handle health changes and relevant calculations? I'll pick through myself if need be, but I figure no need to do unnecessary work.

**Comment by Aliharu** [comment]
The relevant functions are

_setupSquareCounters -> This triggers on startup to set initial values

_onSquareCounterChange -> Triggers when a square box is changed

If somebody could figure it out that would be great.  I've taken multiple cracks at it and can never figure it out.

Just make sure that the willpower boxes still work with whatever changes are made.

**Comment by Aliharu** [comment]
Should be fixed in 1.8.4
